# Generated by Django 5.0.1 on 2024-01-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
